version: "3.7"

services:

  # logging:
  #   container_name: tracker-logging
  #   build: ./logging
  #   ports:
  #     - "12201:12201/udp"
  #   environment:
  #     PORT: 12201
  #     APPINSIGHTS_PERFORMANCE_METRICS: 0
  #     APPINSIGHTS_INSTRUMENTATIONKEY: /run/secrets/APPINSIGHTS_INSTRUMENTATIONKEY
  #     APPLICATION: tracker.otl.gg
  #   secrets:
  #     - APPINSIGHTS_INSTRUMENTATIONKEY
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   entrypoint: /var/logging/start.sh

  db:
    container_name: tracker-db
    build: ./db
    # depends_on:
    #   - logging
    networks:
      - tracker-network
    ports:
      - "27017:27017"
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://localhost:12201"
    environment:
      MONGO_INITDB_DATABASE: tracker
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/MONGO_INITDB_ROOT_USERNAME_FILE
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_INITDB_ROOT_PASSWORD_FILE
      WEB_TRACKER_PASSWORD_FILE: /run/secrets/WEB_TRACKER_PASSWORD_FILE
    secrets:
      - MONGO_INITDB_ROOT_USERNAME_FILE
      - MONGO_INITDB_ROOT_PASSWORD_FILE
      - WEB_TRACKER_PASSWORD_FILE
    restart: always
    # volumes:
    #   - /data/db:/data/db:rw
    #   - /mnt/backup:/data/backup:rw
    entrypoint: /var/mongo/start.sh
    privileged: true

  redis:
    container_name: tracker-redis
    build: ./redis
    # depends_on:
    #   - logging
    networks:
      - tracker-network
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://localhost:12201"
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/REDIS_PASSWORD_FILE
      REDIS_PORT: 6379
    secrets:
      - REDIS_PASSWORD_FILE
    restart: always
    entrypoint: /var/redis/start.sh
    privileged: true

  node:
    container_name: tracker-node
    build: ./node
    depends_on:
      # - logging
      - db
      - redis
    networks:
      - tracker-network
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://localhost:12201"
    environment:
      # APPINSIGHTS_INSTRUMENTATIONKEY: /run/secrets/APPINSIGHTS_INSTRUMENTATIONKEY
      DOMAIN: tracker.otl.gg
      MINIFY_CACHE: 1
      MINIFY_ENABLED: 1
      NODE_ENV: production
      PORT: 3030
      REDIS_PASSWORD_FILE: /run/secrets/REDIS_PASSWORD_FILE
      REDIS_PORT: 6379
      REDIS_PREFIX: tracker
      WEB_TRACKER_PASSWORD_FILE: /run/secrets/WEB_TRACKER_PASSWORD_FILE
    secrets:
      # - APPINSIGHTS_INSTRUMENTATIONKEY
      - REDIS_PASSWORD_FILE
      - WEB_TRACKER_PASSWORD_FILE
    restart: always
    entrypoint: /var/www/start.sh
    privileged: true

  nginx:
    container_name: tracker-nginx
    build: ./nginx
    depends_on:
      # - logging
      - node
    networks:
      - tracker-network
    ports:
      - "80:80"
      - "443:443"
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://localhost:12201"
    environment:
      DOMAIN: tracker.otl.gg
      PROXY_PORT: 3030
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-work:/var/certbot/work:rw
      - nginx-work:/var/nginx/work:rw
    entrypoint: /var/nginx/start.sh

  # certbot:
  #   container_name: tracker-certbot
  #   build: ./certbot
  #   depends_on:
  #     - nginx
  #     - logging
  #   logging:
  #     driver: "gelf"
  #     options:
  #       gelf-address: "udp://localhost:12201"
  #   environment:
  #     DOMAIN: tracker.otl.gg
  #     EMAIL: roncli@roncli.com
  #   restart: always
  #   volumes:
  #     - certbot-conf:/etc/letsencrypt:rw
  #     - certbot-work:/var/certbot/work:rw
  #   entrypoint: /var/certbot/start.sh

networks:
  tracker-network:
    driver: bridge

volumes:
  certbot-conf:
  certbot-work:
  nginx-work:

secrets:
  APPINSIGHTS_INSTRUMENTATIONKEY:
    file: ./secrets/APPINSIGHTS_INSTRUMENTATIONKEY
  MONGO_INITDB_ROOT_PASSWORD_FILE:
    file: ./secrets/MONGO_INITDB_ROOT_PASSWORD_FILE
  MONGO_INITDB_ROOT_USERNAME_FILE:
    file: ./secrets/MONGO_INITDB_ROOT_USERNAME_FILE
  REDIS_PASSWORD_FILE:
    file: ./secrets/REDIS_PASSWORD_FILE
  WEB_TRACKER_PASSWORD_FILE:
    file: ./secrets/WEB_TRACKER_PASSWORD_FILE
